language: objective-c
compiler: clang
xcode_project: UTI.xcodeproj
xcode_scheme: CI
before_install:
  - git clone git://github.com/macmade/XSDocgen
  - cd XSDocgen && make && sudo make install && cd ..
